name: dev

on:
  push:
    branches:
      - LCL-v1.0.0

jobs:

  # check-dependencies:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: 3.11.4

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install cryptography django celery python-dotenv

  #   - name: Run dependency check
  #     run: |
  #       python dependency-check.py || exit 1

  # check-requirements:
  #   runs-on: ubuntu-latest
  #   needs:  [check-dependencies]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: 3.11.4

  #     - name: Cache dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pip-

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Check requirements
  #       run: |
  #         pip check

  #     - name: Compatibility check
  #       run: |
  #         python manage.py check

  #     - name: Deployment check
  #       run: |
  #         python manage.py check --deploy

  # quality-check:
  #   runs-on: ubuntu-latest
  #   needs: [check-requirements]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: 3.11.4

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install flake8 pylint isort black autoflake

  #     - name: Run black formatting
  #       run: |
  #         black .

  #     - name: Run isort
  #       run: |
  #         isort * 
        
  #     - name: Run autoflake8
  #       run : |
  #         autoflake --remove-all-unused-imports --recursive --exclude=services .
  

  merge-test:
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Exclude .github directory
        run: |
          rm -rf .github

      - name: Merge LCL-v1.0.0 to master
        uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: ${{ github.ref }}
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

  # merge-dev:
  #   runs-on: ubuntu-latest
  #   needs:  [check-requirements]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Exclude .github directory
  #       run: |
  #         rm -rf .github

  #     - name: Merge LCL-v1.0.19 to DEV-v1.7
  #       uses: everlytic/branch-merge@1.1.2
  #       with:
  #         github_token: ${{ github.token }}
  #         source_ref: ${{ github.ref }}
  #         target_branch: 'DEV-v1.7'
  #         commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
  
 