name: Portfolio

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Ensure this matches your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Modify if you use a different test command or tool

    - name: Build project
      run: npm run build  # Modify if your build command is different

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Ensure this matches your deployment branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Ensure this matches your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Modify if your build command is different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Ensure this matches your build output directory
